name: Build and Publish to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image to ECR
        run: |
          echo "::set-env name=DOCKER_TAG::$(echo ${GITHUB_SHA::12})"
          docker buildx create --use
          docker buildx build --platform linux/amd64 --push \
            -t your-ecr-repository-url:${DOCKER_TAG} \
            -t your-ecr-repository-url:latest \
            .

          echo "::set-output name=ECR_IMAGE_URL::your-ecr-repository-url:${DOCKER_TAG}"

      - name: Store ECR image URL as an output variable
        id: set-ecr-image-url
        run: echo "ECR_IMAGE_URL=${{ steps.build-and-push.outputs.ECR_IMAGE_URL }}" >> $GITHUB_ENV

  deploy-latest-tag:
    needs: build-and-publish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Create latest tag for ECR image
        run: |
          aws ecr batch-check-layer-availability --repository-name your-ecr-repository-name --image-manifest "{\"imageDigest\":\"$(cat ${GITHUB_ENV} | grep ECR_IMAGE_URL | cut -d'=' -f2)\"}"
          aws ecr put-image --repository-name your-ecr-repository-name --image-manifest "{\"imageDigest\":\"$(cat ${GITHUB_ENV} | grep ECR_IMAGE_URL | cut -d'=' -f2)\"}" --image-tag latest
