name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        run: |
          pip install serverless
          sls plugin install -n serverless-python-requirements

      - name: Deploy Lambda Function
        run: |
          sls deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: your-aws-region  # Replace with your AWS region
